language: node_js
services:
  - mongodb
node_js:
  - 6
env:
  - USE_OLDEST_NPM_VERSIONS=0
  - USE_OLDEST_NPM_VERSIONS=1
before_install:
  - |
    if [ $USE_OLDEST_NPM_VERSIONS -eq 1 ]
    then
      # Test against oldest allowed versions in package.json - Use sed to remove ^ characters
      sed -i 's/"\^/"/g' package.json
      npm i mongoose@5.0.11 reflect-metadata@0.1.8
    else
      npm i mongoose reflect-metadata
    fi
script:
  - npm test